server:
  port: 8080
spring:
  datasource:
    c3p0:
      type: com.mchange.v2.c3p0.ComboPooledDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/blog
      driver-class-name: com.mysql.cj.jdbc.Driver
      user: root
      password: 123456
      maxPoolSize: 10
      minPoolSize: 5
      initialPoolSize: 3
      autoCommitOnClose: false
      maxIdleTime: 3000
      idleConnectionTestPeriod: 60
      checkoutTimeout: 10000
      acquireIncrement: 3
# application.yml
logging:
  level:
    com.example.mybatisplus_c3p0.mapper: debug



